table Sale
	lineageTag: a1b2c3d4-e5f6-7890-abcd-ef0123456789

	measure 'Total Revenue' = SUM(Sale[revenue])
		formatString: $#,0.00;($#,0.00);$#,0.00
		lineageTag: 11111111-1111-1111-1111-111111111111

	measure 'Total Profit' = SUM(Sale[profit])
		formatString: $#,0.00;($#,0.00);$#,0.00
		lineageTag: 22222222-2222-2222-2222-222222222222

	measure 'Average Revenue' = AVERAGE(Sale[revenue])
		formatString: $#,0.00;($#,0.00);$#,0.00
		lineageTag: 33333333-3333-3333-3333-333333333333

	measure 'Transaction Count' = COUNTROWS(Sale)
		formatString: #,0
		lineageTag: 44444444-4444-4444-4444-444444444444

	column sale_id
		dataType: int64
		formatString: 0
		lineageTag: aaaa0001-0000-0000-0000-000000000000
		summarizeBy: none
		sourceColumn: sale_id

	column date
		dataType: dateTime
		formatString: General Date
		lineageTag: aaaa0002-0000-0000-0000-000000000000
		summarizeBy: none
		sourceColumn: date

	column store_id
		dataType: int64
		formatString: 0
		lineageTag: aaaa0003-0000-0000-0000-000000000000
		summarizeBy: none
		sourceColumn: store_id

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: aaaa0004-0000-0000-0000-000000000000
		summarizeBy: none
		sourceColumn: product_id

	column region
		dataType: string
		lineageTag: aaaa0005-0000-0000-0000-000000000000
		summarizeBy: none
		sourceColumn: region

	column category
		dataType: string
		lineageTag: aaaa0006-0000-0000-0000-000000000000
		summarizeBy: none
		sourceColumn: category

	column revenue
		dataType: double
		formatString: $#,0.00;($#,0.00);$#,0.00
		lineageTag: aaaa0007-0000-0000-0000-000000000000
		summarizeBy: sum
		sourceColumn: revenue

	column profit
		dataType: double
		formatString: $#,0.00;($#,0.00);$#,0.00
		lineageTag: aaaa0008-0000-0000-0000-000000000000
		summarizeBy: sum
		sourceColumn: profit

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: aaaa0009-0000-0000-0000-000000000000
		summarizeBy: sum
		sourceColumn: quantity

	partition Sale = m
		mode: import
		source =
			let
			    Source = #table(
			        type table [sale_id = Int64.Type, date = DateTime.Type, store_id = Int64.Type, product_id = Int64.Type, region = Text.Type, category = Text.Type, revenue = Number.Type, profit = Number.Type, quantity = Int64.Type],
			        {
			            {1, #datetime(2024, 1, 15, 0, 0, 0), 1, 1, "East", "Electronics", 1200.50, 360.15, 5},
			            {2, #datetime(2024, 1, 16, 0, 0, 0), 2, 2, "West", "Clothing", 850.00, 255.00, 12},
			            {3, #datetime(2024, 2, 1, 0, 0, 0), 3, 3, "North", "Food", 420.75, 126.23, 25},
			            {4, #datetime(2024, 2, 15, 0, 0, 0), 1, 4, "East", "Home", 1580.00, 474.00, 3},
			            {5, #datetime(2024, 3, 1, 0, 0, 0), 4, 1, "South", "Electronics", 2100.00, 630.00, 8},
			            {6, #datetime(2024, 3, 15, 0, 0, 0), 2, 3, "West", "Food", 310.25, 93.08, 18},
			            {7, #datetime(2024, 4, 1, 0, 0, 0), 3, 2, "North", "Clothing", 675.00, 202.50, 9},
			            {8, #datetime(2024, 4, 15, 0, 0, 0), 4, 4, "South", "Home", 920.00, 276.00, 4},
			            {9, #datetime(2024, 5, 1, 0, 0, 0), 1, 3, "East", "Food", 540.00, 162.00, 30},
			            {10, #datetime(2024, 5, 15, 0, 0, 0), 2, 1, "West", "Electronics", 1750.00, 525.00, 6},
			            {11, #datetime(2024, 6, 1, 0, 0, 0), 3, 4, "North", "Home", 1100.00, 330.00, 2},
			            {12, #datetime(2024, 6, 15, 0, 0, 0), 4, 2, "South", "Clothing", 480.00, 144.00, 15}
			        }
			    )
			in
			    Source

